In [4]:
import numpy as np
np.linspace(20,51,7)


array([20.        , 25.16666667, 30.33333333, 35.5       , 40.66666667,
       45.83333333, 51.        ])

In [8]:
a= np.logspace(20,50,2)
np.e**a

C:\Users\SINCHAN BASU\AppData\Local\Temp\ipykernel_9444\3630202766.py:2: RuntimeWarning: overflow encountered in power
  np.e**a


array([inf, inf])

In [6]:
np.e

2.718281828459045

In [10]:
np.arange(20,51,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])