In [1]:
import numpy as np
import torch

In [2]:
# Input(temp,rainfall,humidity)
inputs = np.array([[73,67,43],
                  [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]], dtype='float32')

In [3]:
# Targets (apples,oranges)
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [6]:
# Weights and biases
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 2.1141, -0.5930, -0.1706],
        [-0.3834, -0.6604,  0.8472]], requires_grad=True)
tensor([ 0.0101, -1.3180], requires_grad=True)


In [7]:
def model(x):
    return x @ w.t() + b

In [8]:
# Generate Predictions
preds = model(inputs)
print(preds)

tensor([[107.2723, -37.1223],
        [129.2904, -40.1004],
        [ 94.5784, -74.0273],
        [183.8378, -37.4751],
        [ 77.0121, -31.8653]], grad_fn=<AddBackward0>)


In [9]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [10]:
# Mean squared error(mse) loss
def mse(t1,t2):
    diff=t1-t2
    return torch.sum(diff*diff)/diff.numel()

In [11]:
# Compute loss
loss = mse(preds,targets)
print(loss)

tensor(13497.5781, grad_fn=<DivBackward0>)


In [12]:
# Compute gradients
loss.backward()

In [13]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 2.1141, -0.5930, -0.1706],
        [-0.3834, -0.6604,  0.8472]], requires_grad=True)
tensor([[  4145.3828,   1775.2974,   1609.5371],
        [-11335.5215, -13004.2373,  -7792.0830]])


In [14]:
w
w.grad

tensor([[  4145.3828,   1775.2974,   1609.5371],
        [-11335.5215, -13004.2373,  -7792.0830]])

In [15]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [16]:
# Let's verify that the loss is actually lower
loss = mse(preds,targets)
print(loss)

tensor(13497.5781, grad_fn=<DivBackward0>)


In [17]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [18]:
'''
Train the model using gradient descent
1. Generate predictions
2. Calculate the loss
3. Compute gradients w.r.t. the weights and biases
4. Adjust the weights by subtracting a small quantity proportional to the gradient
5. Reset the gradients to zero
'''

'\nTrain the model using gradient descent\n1. Generate predictions\n2. Calculate the loss\n3. Compute gradients w.r.t. the weights and biases\n4. Adjust the weights by subtracting a small quantity proportional to the gradient\n5. Reset the gradients to zero\n'

In [19]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[102.3642, -16.7826],
        [122.9253, -13.3530],
        [ 87.6590, -42.2189],
        [178.2502, -17.4366],
        [ 71.3204,  -6.1039]], grad_fn=<AddBackward0>)


In [20]:
# Calculate the loss
loss = mse(preds,targets)
print(loss)

tensor(10023.1191, grad_fn=<DivBackward0>)


In [21]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  3644.9512,   1254.7317,   1284.5582],
        [ -9234.0020, -10741.5176,  -6396.8745]])
tensor([  36.3038, -111.1790])


In [22]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [23]:
print(w)
print(b)

tensor([[ 2.0362, -0.6233, -0.1995],
        [-0.1777, -0.4229,  0.9891]], requires_grad=True)
tensor([ 0.0093, -1.3155], requires_grad=True)


In [24]:
# Calculate loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(7670.1689, grad_fn=<DivBackward0>)


In [25]:
# Training for multiple epochs
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds,targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [26]:
# Calculate the loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor(831.9630, grad_fn=<DivBackward0>)


In [27]:
# Predictions
preds

tensor([[ 69.7176,  73.3937],
        [ 86.4207, 106.5831],
        [ 88.9296, 114.5475],
        [ 93.6067,  56.6057],
        [ 66.9284, 117.7333]], grad_fn=<AddBackward0>)

In [28]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [29]:
# Linear regression using PyTorch built-ins
# Torch.nn package contains utility classes for building neural networks.
import torch.nn as nn

In [32]:
# Input (temp,rainfall,humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [33]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [34]:
# Dataset and DataLoader which allows access to rows from inputs and targets as tuples, and provides standard APIs for working with many different types of datasets in PyTorch.
from torch.utils.data import TensorDataset

In [35]:
# Define Dataset
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [36]:
from torch.utils.data import DataLoader

In [37]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [38]:
for xb,yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 91.,  87.,  65.],
        [ 73.,  67.,  43.],
        [ 68.,  97.,  70.],
        [ 88., 134.,  59.],
        [ 69.,  96.,  70.]])
tensor([[ 80., 102.],
        [ 56.,  70.],
        [102., 120.],
        [118., 132.],
        [103., 119.]])


In [39]:
# nn.Linear : Instead of initializing the weights & biases manually, we can define the model using the nn.Linear class from PyTorch, which does it automatically.
# Define model
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.2366, -0.4527, -0.4278],
        [-0.4645, -0.2203, -0.3634]], requires_grad=True)
Parameter containing:
tensor([-0.2510,  0.1763], requires_grad=True)


In [40]:
# Prameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2366, -0.4527, -0.4278],
         [-0.4645, -0.2203, -0.3634]], requires_grad=True),
 Parameter containing:
 tensor([-0.2510,  0.1763], requires_grad=True)]

In [41]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-31.7096, -64.1193],
        [-45.9425, -84.7382],
        [-65.1461, -90.8338],
        [-11.4177, -70.1222],
        [-57.3352, -78.4619],
        [-31.0203, -64.3635],
        [-45.9176, -84.8813],
        [-65.3373, -91.6617],
        [-12.1070, -69.8780],
        [-57.9996, -78.3608],
        [-31.6847, -64.2624],
        [-45.2532, -84.9824],
        [-65.1709, -90.6907],
        [-10.7534, -70.2233],
        [-58.0244, -78.2177]], grad_fn=<AddmmBackward0>)

In [42]:
# Import nn.functional
import torch.nn.functional as F

In [43]:
# Define loss function
loss_fn = F.mse_loss

In [44]:
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(23757.0254, grad_fn=<MseLossBackward0>)


In [45]:
'''
Optimizer
Instead of manually manipulating the model's weights & biases using gradients, we can use the optimizer optim.SGD. SGD is short for "stochastic gradient descent". The term stochastic indicates that samples are selected in random batches instead of as a single group.
'''
# Define optimizer
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [48]:
# Train the model
# Using fit that trains the model for a given number of epochs
# Utility function to train the model
def fit(num_epochs,model,loss_fn,opt,train_dl):
    # Repeat for given number of epochs:
    for epochs in range(num_epochs):
        # Train with batches of data :
        for xb,yb in train_dl:
            # 1. Generate predictions
            pred=model(xb)
            # 2. Calculate loss
            loss = loss_fn(pred,yb)
            # 3. Compute gradients
            loss.backward()
            # 4. Update paramters using gradients
            opt.step()
            # 5. Reset the gradients to zero
            opt.zero_grad()
        # Print the progress
        if(epochs+1)%10 == 0:
            print('Epoch[{}/{}], Loss: {:.4f}'.format(epochs+1,num_epochs,loss.item()))

In [49]:
fit(100,model,loss_fn,opt,train_dl)

Epoch[10/100], Loss: 60.5550
Epoch[20/100], Loss: 45.0657
Epoch[30/100], Loss: 37.5797
Epoch[40/100], Loss: 22.3782
Epoch[50/100], Loss: 22.8713
Epoch[60/100], Loss: 24.3661
Epoch[70/100], Loss: 37.5266
Epoch[80/100], Loss: 16.6973
Epoch[90/100], Loss: 16.7461
Epoch[100/100], Loss: 24.7296


In [51]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.5766,  70.9348],
        [ 79.8201,  97.9670],
        [123.1303, 138.3888],
        [ 23.7092,  39.9302],
        [ 96.2091, 112.7495],
        [ 56.3161,  69.8132],
        [ 79.2121,  97.5583],
        [123.1851, 138.7186],
        [ 24.9697,  41.0518],
        [ 96.8616, 113.4624],
        [ 56.9686,  70.5260],
        [ 78.5596,  96.8454],
        [123.7383, 138.7975],
        [ 23.0567,  39.2173],
        [ 97.4696, 113.8712]], grad_fn=<AddmmBackward0>)

In [52]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [53]:
model(torch.tensor([[75,63,44.]]))

tensor([[53.4860, 67.3527]], grad_fn=<AddmmBackward0>)