In [4]:
import torch
t1=torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [5]:
# Vector
t2=torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [7]:
# Matrix
t3=torch.tensor([[5.,6],[7,8],[9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [12]:
t4=torch.tensor([[[11,12,13],
                [13,14,15]],
                [[15,16,17],
                [17,18,19.]]])

In [8]:
t1.shape

torch.Size([])

In [9]:
t2.shape

torch.Size([4])

In [10]:
t3.shape

torch.Size([3, 2])

In [13]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [14]:
# Create Tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x , w , b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [15]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [16]:
# Compute Derivates
y.backward()

In [17]:
# Display Gradients
print('dy/dx : ',x.grad)
print('dy/dw : ',w.grad)
print('dy/db : ',b.grad)

dy/dx :  None
dy/dw :  tensor(3.)
dy/db :  tensor(1.)


In [19]:
import numpy as np
x = np.array([[1,2],[3,4.0]])
x

array([[1., 2.],
       [3., 4.]])

In [21]:
# Convert numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [22]:
x.dtype,y.dtype,w.dtype,b.dtype

(dtype('float64'), torch.float64, torch.float32, torch.float32)

In [1]:
import numpy as np
import torch

In [2]:
# Input (temp,rainfall,humidity)
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
